//NAVBAR
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const SET_LINKS = 'SET_LINKS';

//HOME
export const SET_FEATURES_CARDS = 'SET_FEATURES_CARDS';

//YEGUADA   
export const SET_HORSES = 'SET_HORSES';
export const SET_HORSES_CONTENT = 'SET_HORSES_CONTENT';
export const CHANGE_HORSES_CONTENT = 'CHANGE_HORSES_CONTENT';

// SHOP
export const SET_DATES = 'SET_DATES';
export const ADD_ACTIVITY_DATE = 'ADD_ACTIVITY_DATE';